language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

before_install:
  - docker build -t agagno/learn-repo-demo -f ./demoproject/docker/Dockerfile.dev .

script:
  #- docker run -e CI=true agagno/learn-repo-demo  npm run test -- --coverage
  - docker run -e CI=true agagno/learn-repo-demo  java -jar ./app.jar
