language: java

sudo: required
services:
  - docker

before_install:
  - docker build -t agagno/learn-repo-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true agagno/learn-repo-demo  npm run test -- --coverage
